### PR TITLE
Changes to support a fairly significant refactor

### PR DESCRIPTION
**Pull request by ndroo**
For this to to work you need to:
1) Ensure the php/apache process has write/read access to site/template_c (this is for smarty)
i.e. 'sudo chmod 777 site/template_c' (this is a bad example for prod, but it will work)
2) Run the db changes in the migrations/00001_refactor.sql

Let me know if you have any issues!

### CODE REVIEW

**Comment by ndroo** [comment]
Additionally: Please confirm the heal cron still works, i just had to make an adjustment but i'm not sure what the expected behaviour should be. (see this commit: https://github.com/ndroo/squealing-funicular/commit/6bd2b86a3d4d75737636c220b71304f8e864e8f1)

**Comment by ndroo** [comment]
Huzzah!

**Comment by amosr** [comment]
heal cron no good :-(

**Comment by amosr** [comment]
:+1:

**Comment by ndroo** [comment]
@amosr i made another pull request to address the heal cron https://github.com/kroony/squealing-funicular/pull/6 The issue is due to the servers php version not supporting things like $a->function()->property. Had to split it across multiple lines.

**Comment by amosr** [comment]
lol - stupid php

**Pull request merged**
